enable_this_plugin: true
enable_permission:
  kart_ride: true
  kart_drift: true
  cmd_menu: true
  cmd_entry: true
  cmd_exit: true
  cmd_character: true
  cmd_characterreset: true
  cmd_kart: true
  cmd_leave: true
  cmd_ranking: true
  cmd_item: true
  cmd_other_menu: true
  cmd_other_entry: true
  cmd_other_exit: true
  cmd_other_character: true
  cmd_other_characterreset: true
  cmd_other_kart: true
  cmd_other_leave: true
  cmd_other_ranking: true
  cmd_other_item: true
  use_item: true
  interact_object: true
enable_op_permission:
  kart_remove: true
  cmd_circuit: true
  cmd_display: true
  cmd_reload: true
  cmd_itemboxtool: true
enable_scoreboard: true
disabled_worlds:
- testworld
- testworld2
settings:
  start_block_id: '41:0'
  goal_block_id: '42:0'
  dirt_block_id: '12:0'
  item_slot: 2
item:
  tier1: 30
  tier2: 60
  tier3: 80
  dash_board:
    effect_level: 4
    effect_second: 2