#
# ------------------------- 概要 -------------------------
#
# プラグインの汎用的な機能の設定を変更できるコンフィグファイルです。
#
# ------------------------- 汎用設定 -------------------------
#

# 当プラグインから送信されるメッセージ、及びコンフィグファイルに記載される補足説明に使用される言語を設定します。
language: ja_JP

# 当プラグインの機能を有効にします。
enable_this_plugin: true

# スコアボードを有効にします。
enable_scoreboard: true

# 当プラグインが動作しないワールド名を指定します。
disabled_worlds:
- "testworld"
- "testworld2"

# レース設定
settings:

  # スタートブロックのIDを変更します。
  start_block_id: "41:0"

  # ゴールブロックのIDを変更します。
  goal_block_id: "42:0"

  # ダートブロックのIDを変更します。
  dirt_block_id: "12:0"

  # レース中使用できるアイテムスロットの数を変更します。
  item_slot: 2

# アイテム設定
item:

  #tierは、アイテムボックスに接触した際に順位に応じたアイテムを付与するための設定です。
  #アイテム毎にtierが設定されており、tier1～tier4の4つの階級があります。
  #階級が高いほど効果の強いアイテムが多くなります。

  #プレイヤーの上位「0％～tier1％」のプレイヤーには階級1のアイテムのみ与えられます。
  #デフォルトでは、上位0％～30％のプレイヤーに設定されています。
  tier1: 30

  #プレイヤーの上位「tier1％～tier2」％のプレイヤーには階級1～階級2のアイテムのみ与えられます。
  #デフォルトでは、上位30％～60％のプレイヤーに設定されています。
  tier2: 60

  #プレイヤーの上位「tier2％～tier3％」のプレイヤーには階級2～階級3のアイテムのみ与えられます。
  #デフォルトでは、上位60％～80％のプレイヤーに設定されています。
  tier3: 80

  #残りの、上位tier3％～100％のプレイヤーには階級3～階級4のアイテムのみ与えられます。
  #デフォルトでは、上位80％～100％のプレイヤーに設定されています。

  # ダッシュボード設定
  dash_board:

    # スピードポーションエフェクトのLVを変更します。
    effect_level: 4

    # スピードポーションエフェクトの秒数を変更します。
    effect_second: 2

  # チェックポイントの検出範囲設定。
  detect_checkpoint_radius:

    # チェックポイントツールで設置したチェックポイントとの距離が、この項目で設定した数値(ブロック数)以内に差し掛かった場合、
    # チェックポイントを通過したと判定されます。
    # 100を超える数値は実際の処理では100として扱われます。
    tier1: 30

    # チェックポイントツールTier2で設置したチェックポイントとの距離が、この項目で設定した数値(ブロック数)以内に差し掛かった場合、
    # チェックポイントを通過したと判定されます。
    # 100を超える数値は実際の処理では100として扱われます。
    tier2: 40

    # チェックポイントツールTier3で設置したチェックポイントとの距離が、この項目で設定した数値(ブロック数)以内に差し掛かった場合、
    # チェックポイントを通過したと判定されます。
    # 100を超える数値は実際の処理では100として扱われます。
    tier3: 50