language: ja_JP
enable_this_plugin: true
enable_scoreboard: true
disabled_worlds:
- "testworld"
- "testworld2"
settings:
  start_block_id: "41:0"
  goal_block_id: "42:0"
  dirt_block_id: "12:0"
  item_slot: 2
item:
  tier1: 30
  tier2: 60
  tier3: 80
  dash_board:
    effect_level: 4
    effect_second: 2
  detect_checkpoint_radius:
    tier1: 30
    tier2: 40
    tier3: 50