name: YPLKart
main: com.github.erozabesu.yplkart.YPLKart
version: 2.0.3
softdepend: [Vault]
commands:
  ka:
    description: Basic command.Display command reference.
permissions:
  YPLKart.cmd.ka:
    default: true