name: YPLKart
main: main.java.com.github.erozabesu.YPLKart.YPLKart
version: 1.0.4
commands:
  ka:
    description: Basic command.Display command reference.
permissions:
  YPLKart.cmd.ka:
    default: true