name: YPLKart
main: com.github.erozabesu.yplkart.YPLKart
version: 1.0.9
commands:
  ka:
    description: Basic command.Display command reference.
permissions:
  YPLKart.cmd.ka:
    default: true